### ISSUE TITLE
Receptor density panel occassionally incomplete althouth data is available 

### ISSUE THREAD

**Issue by dickscheid** [FZJ-INM1-BDA/siibra-explorer#1015] opened 2021-09-07 06:38 UTC
The panel for receptor densities does sometimes only show the textual description, not the fingerprint and profiles, although they are available for this region. This is not to be confused with plain EBRAINS features for receptors - it happens for the explicit receptor feature type.

My feeling is that it is related to how quickly a user clicks the entry. Is it possible that if a user clicks the feature too early, the profile/fingerpinrt data is not yet completely loaded and therefore not shown?

It happened to me, for example, in hOc1 where such data is definitly available. After selecting the feature a few times in sequence, and possibly selecting a different area in between, the feature was displayed correctly.

**Comment by xgui3783** [comment] 2022-11-03 14:36
cannot reproduce in latest (2.7.6)

closing for now. 

feel free to re-open if the issue persist

**Closed by xgui3783** 2022-11-03 14:36 UTC
Labels: bug
