### ISSUE TITLE
Color scheme not preserved when coming back via browser histroy

### ISSUE THREAD

**Issue by dickscheid** [FZJ-INM1-BDA/siibra-explorer#1040] opened 2021-10-06 06:12 UTC
When browsing the Julich-Brain in Colin space, then switching to another space (e.g. BigBrain) and later returning to Colin by going back in browser history, the RGB colors are not anymore the default ones. While a refresh will bring back teh intended colors, this is disturbing.

default colors:
![grafik](https://user-images.githubusercontent.com/1436846/136149970-3512aebe-38a6-4c2c-902a-abbadda877f7.png)

colors when returning to the same view fro another reference space via browser history:
![grafik](https://user-images.githubusercontent.com/1436846/136149825-18a64887-d01c-43f6-88e5-74d6ef15155c.png)

**Comment by xgui3783** [comment] 2022-11-03 14:34
cannot reproduce, closing. feel free to reopen if the issue persist

**Closed by xgui3783** 2022-11-03 14:34 UTC
Labels: bug
